name: repository and schedule dispatch
on:
  repository_dispatch:
    types: [caller_dispatch]
  schedule:
    - cron: "*/5 * * * *"
jobs:
  processing-caller:
    runs-on: ubuntu-latest
    steps:
     - name: Print schedule message
       if: ${{github.event_name == 'schedule' }}
       run: |
        echo "agendamento executado"

     - name: Print payload
       if: ${{github.event_name != 'schedule' }}
       run: |
        echo "${{ github.event.client_payload.message }}"
