name: repository and schedule dispatch
on:
  repository_dispatch:
    types: [caller_dispatch]
  schedule:
    - cron: "*/5 * * * *"
jobs:
  processing-caller:
    runs-on: ubuntu-latest
    steps:
     - name: Print schedule message
       id: schedule-task-called
       if: ${{github.event_name == 'schedule' }}
       run: |
        response=$(curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN_PAT" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/abauruel/automation-central/actions/artifacts)

        echo "$response"
        artifacts_exist=$(echo "$response" | jq 'has("artifacts") and .artifacts != null')
        if [[ "$artifacts_exist" != "true" ]]; then
            echo "Erro: A resposta não contém a chave 'artifacts' ou a chave é null."
            exit 1
        fi

        is_array=$(echo "$response" | jq '.artifacts | if type == "array" then true else false end')
        array_length=$(echo "$response" | jq '.artifacts | length')

        if [[ "$is_array" != "true" || "$array_length" -eq 0 ]]; then
            echo "Warning: Nenhum artefato encontrado"
            exit 1
        fi

        oldest_artifact=$(echo "$response" | jq '.artifacts | sort_by(.created_at) | .[0]')
        oldest_artifact_id=$(echo "$oldest_artifact" | jq -r '.id')
        oldest_artifact_name=$(echo "$oldest_artifact" | jq -r '.name')
        
        echo "oldest_artifact_id=$oldest_artifact_id" >> $GITHUB_OUTPUT
        echo "oldest_artifact_name=$oldest_artifact_name" >> $GITHUB_OUTPUT

     - name: task for schedule 
       if: ${{ success() }}
       run: |
        artifact_id=${{steps.schedule-task-called.outputs.oldest_artifact_id}}
        echo "executa a consulta ...."
        echo "remove artefato"
        curl -L \
        -X DELETE \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN_PAT" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/abauruel/automation-central/actions/artifacts/$((artifact_id))

        echo "disable workflow scheduled"
        WORKFLOW_ID="schedule_and_repository_dispatch.yaml"
        curl -L \
        -X PUT \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN_PAT" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/abauruel/automation-central/actions/workflows/$WORKFLOW_ID/disable



     - name: Print payload
       if: ${{github.event_name != 'schedule' }}
       run: |
        echo "${{ github.event.client_payload.message }}"
       
